# fly.toml app configuration file generated for hypertext-blog on 2023-09-30T15:04:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hypertext-blog"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV="production"
  LOG_LEVEL="info"
  HOST_URL="https://blog.jacobzweifel.com"
